### PR TITLE
Fix default worker capacity

### LINKED ISSUE #1456: Miscalculating default worker capacity
We found few issues when calculating default worker capacity such as:

- Don't include budgetBufferCapacity when calculating worker capacity
- Scope worker capacity to disk space  as well
- Make rounding worker capacity to power of two doesn't exceed total memory size

### PR DESCRIPTION
**Pull request by akrambek**
Fix #1456

### CODE REVIEW

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java [hunk 1]
```diff
@@ -385,17 +385,32 @@ private static int defaultWorkersCapacity(
...
+        long maxAllowedForBuffers = Math.min(maxAllowedForMemory, usableDiskSpace);
 
         // Streams + Pool
         long bufferCapacity = slotCapacity + slotCapacity;
-        long eventsBufferCapacity = ENGINE_EVENTS_BUFFER_CAPACITY.get(config);
-        long budgetBufferCapacity = BudgetsLayout.SIZEOF_BUDGET_ENTRY * 512L;
-        long totalBufferCapacity = numberOfCores * (bufferCapacity + budgetBufferCapacity + eventsBufferCapacity);
-        int newWorkersCapacity = (int) (maxAllowedForBuffers / totalBufferCapacity);
+        long budgetBufferCapacity = BudgetsLayout.SIZEOF_BUDGET_ENTRY;
+        long totalBufferCapacity = numberOfCores * (bufferCapacity + budgetBufferCapacity);
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java:400]: I realized that although we default `workers` to `available processors`, the calculation should actually be based on `workers`, not `numberOfCores`.

So, we actually only need `osBean` for `getTotalMemorySize()`.

For workers, we would do this instead.
```
int workers = ENGINE_WORKERS.getAsInt(config);
```

Also, for clarity suggest we do the following:
```
int workerBufferCapacity = slotCapacity + slotCapacity + budgetBufferCapacity;
int totalBufferCapacity = workerBufferCapacity * workers;
```

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java [hunk 2]
```diff
@@ -385,17 +385,32 @@ private static int defaultWorkersCapacity(
...
         final double percentMemory = ENGINE_MEMORY_PERCENTAGE.get(config);
+        final int totalEventsBufferCapacity = ENGINE_EVENTS_BUFFER_CAPACITY.get(config) * numberOfCores;
 
-        long maxAllowedForBuffers = (long) (percentMemory * totalMemorySize);
+        long maxAllowedForMemory = (long) (percentMemory * totalMemorySize) - totalEventsBufferCapacity;
+
+        Path directory = Paths.get(ENGINE_DIRECTORY.get(config));
+        long usableDiskSpace = directory.toFile().getUsableSpace();
+
+        long maxAllowedForBuffers = Math.min(maxAllowedForMemory, usableDiskSpace);
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java:395]:
```suggestion
        long maxMemoryBufferCapacity = (long) (percentMemory * totalMemorySize) - totalEventsBufferCapacity;

        Path directory = Paths.get(ENGINE_DIRECTORY.get(config));
        long usableDiskSpace = directory.toFile().getUsableSpace()

        double percentDisk = ENGINE_DISK_PERCENTAGE.get(config);
        long maxDiskBufferCapacity = (long) (percentDisk * usableDiskSpace);

        long maxBufferCapacity = Math.min(maxMemoryBufferCapacity, maxDiskBufferCapacity);
```

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java [hunk 3]
```diff
@@ -385,17 +385,32 @@ private static int defaultWorkersCapacity(
...
 
         // Streams + Pool
         long bufferCapacity = slotCapacity + slotCapacity;
-        long eventsBufferCapacity = ENGINE_EVENTS_BUFFER_CAPACITY.get(config);
-        long budgetBufferCapacity = BudgetsLayout.SIZEOF_BUDGET_ENTRY * 512L;
-        long totalBufferCapacity = numberOfCores * (bufferCapacity + budgetBufferCapacity + eventsBufferCapacity);
-        int newWorkersCapacity = (int) (maxAllowedForBuffers / totalBufferCapacity);
+        long budgetBufferCapacity = BudgetsLayout.SIZEOF_BUDGET_ENTRY;
+        long totalBufferCapacity = numberOfCores * (bufferCapacity + budgetBufferCapacity);
+        int newWorkersCapacity = (int) (maxAllowedForBuffers  / totalBufferCapacity);
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java:401]:
```suggestion
        int newWorkersCapacity = Integer.highestOneBit((int) (maxBufferCapacity  / totalBufferCapacity));
```

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java [hunk 4]
```diff
@@ -385,17 +385,32 @@ private static int defaultWorkersCapacity(
...
+        long requiredForRoundedUp = (long) roundedUp * totalBufferCapacity;
+
+        if (requiredForRoundedUp <= maxAllowedForBuffers)
+        {
+            newWorkersCapacity = roundedUp;
+        }
+        else
+        {
+            newWorkersCapacity = Math.max(1, roundedUp >> 1);
+        }
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java:413]: With the use of `Integer.highestOneBit(...)` above, we can remove this, agree?

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
