### PR TITLE
Don't send window before connection budgetId is assigned

### LINKED ISSUE #548: BudgetDebitor fails to claim budget after sometime
```
org.agrona.concurrent.AgentTerminationException: java.lang.IllegalStateException: missing file for budgets : /Users/akramyakubov/workspace/aklivity/local-zilla/.zilla/engine/budgets127
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:707)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: missing file for budgets : /Users/akramyakubov/workspace/aklivity/local-zilla/.zilla/engine/budgets127
	at org.agrona.core/org.agrona.IoUtil.checkFileExists(IoUtil.java:507)
	at org.agrona.core/org.agrona.IoUtil.mapExistingFile(IoUtil.java:396)
	at org.agrona.core/org.agrona.IoUtil.mapExistingFile(IoUtil.java:361)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.layouts.BudgetsLayout$Builder.build(BudgetsLayout.java:144)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.newBudgetDebitor(DispatchAgent.java:1620)
	at org.agrona.core/org.agrona.collections.Int2ObjectHashMap.computeIfAbsent(Int2ObjectHashMap.java:268)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.supplyDebitor(DispatchAgent.java:536)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.budget.KafkaMergedBudgetAccountant.supplyDebitor(KafkaMergedBudgetAccountant.java:49)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientGroupFactory$ClusterClient.onNetworkWindow(KafkaClientGroupFactory.java:1890)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientGroupFactory$ClusterClient.onNetwork(KafkaClientGroupFactory.java:1757)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool.doWindow(KafkaClientConnectionPool.java:424)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.doStreamWindow(KafkaClientConnectionPool.java:805)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.doStreamBegin(KafkaClientConnectionPool.java:818)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.onStreamBegin(KafkaClientConnectionPool.java:668)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.onStreamSignal(KafkaClientConnectionPool.java:992)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientConnection.onConnectionSignal(KafkaClientConnectionPool.java:1466)
	at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientConnection.onConnectionMessage(KafkaClientConnectionPool.java:1327)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1119)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:1041)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
	at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:701)
	... 3 more
	Suppressed: java.lang.Exception: [engine/data#9]	[0x0909000000000231] streams=[consumeAt=0x0002eec8 (0x000000000082eec8), produceAt=0x0002efe0 (0x000000000082efe0)]
		at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:705)
		... 3 more
stopped
┌─(~/workspace/ak
```

### PR DESCRIPTION
**Pull request by akrambek**
## Description

BudgetDebitor fails to claim budget after sometime

Fixes #548

### CODE REVIEW

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientConnectionPool.java [hunk 1]
```diff
@@ -1077,6 +1078,12 @@ private void doConnectionBegin(
             if (KafkaState.closed(state))
             {
                 state = 0;
+                initialAck = 0;
+                initialSeq = 0;
+                initialMax = 0;
+                replyAck = 0;
+                replySeq = 0;
+                initialBudId = NO_BUDGET_ID;
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientConnectionPool.java:1086]: Excellent catch 👍

**Review by jfallows — APPROVED** [review]
