### PR TITLE
Zilla is validating env vars before replacing them

### LINKED ISSUE #795: Zilla is validating `env` vars before replacing them.
**Describe the bug**
Zilla is validating `env` vars before replacing them. 

```
[23,31][/telemetry/exporters/prometheus_metric_exporter/options/endpoints/0/port] The value must be of integer type, but actual type is string.
error
io.aklivity.zilla.runtime.engine.config.ConfigException: Engine configuration failed
```

**To Reproduce**
```
docker run -v ./zilla.yaml:/etc/zilla/zilla.yaml --env PORT="7190" ghcr.io/aklivity/zilla:0.9.68 start -v
```
zilla.yaml
```
---
name: example
bindings:
  north_tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 12345
    exit: north_echo_server
  north_echo_server:
    type: echo
    kind: server

telemetry:
  exporters:
    prometheus_metric_exporter:
      type: prometheus
      options:
        endpoints:
          - scheme: http
            path: /metrics
            port: ${{env.PORT}}
```

### PR DESCRIPTION
**Pull request by akrambek**
## Description

Zilla is validating env vars before replacing them

Fixes #795

### CODE REVIEW

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java [hunk 1]
```diff
@@ -190,7 +190,7 @@ private boolean validateAnnotatedSchema(
         validate:
         try
         {
-            final JsonObject annotatedSchemaObject = (JsonObject) annotateJsonObject(schemaObject);
+            final JsonObject annotatedSchemaObject = jsonAnnotator.apply(schemaObject);
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java:193]:
```suggestion
final EngineConfigAnnotator annotator = new EngineConfigAnnotator();
final JsonObject annotatedSchemaObject = annotator.annotate(schemaObject);
```

Given the state needed by internals of annotator, suggest we just instantiate this here on stack and call the annotate method directly instead of having a field.

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+    private final Deque<String> schemaKeys;
+    private final Deque<Integer> schemaIndexes;
+
+    public EngineConfigAnnotator()
+    {
+        this.schemaKeys = new LinkedList<>();
+        this.schemaIndexes = new LinkedList<>();
+    }
+
+    public JsonObject annotateJson(
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java:41]:
```suggestion
    public JsonObject annotate(
```

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+import jakarta.json.Json;
+import jakarta.json.JsonArray;
+import jakarta.json.JsonArrayBuilder;
+import jakarta.json.JsonObject;
+import jakarta.json.JsonObjectBuilder;
+import jakarta.json.JsonValue;
+
+import org.agrona.collections.MutableInteger;
+
+public final class EngineConfigAnnotator
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java:30]: Please add `EngineConfigAnnotatorTest` to verify some of the important scenarios.

**Review by jfallows — CHANGES_REQUESTED** [review]

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java (hunk 3 above)
Comment (akrambek) [reply runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java:30]: Sounds good just wanted to check if that what you mean

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java (hunk 1 above)
Comment (akrambek) [reply runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java:193]: That's what I was thinking but then thought that you have resaon

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+{
+    private final LinkedList<String> schemaKeys;
+    private final LinkedList<Integer> schemaIndexes;
+
```
Comment (akrambek) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java:33]: Used implementation because I need an interface from both the deque and the list. Let me know if this is wrong

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java [hunk 5]
```diff
@@ -61,6 +57,8 @@ public final class EngineConfigReader
     private final Resolver expressions;
     private final Collection<URL> schemaTypes;
     private final Consumer<String> logger;
+    private final EngineConfigAnnotator annotator;
+
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java:61]: Please remove this field.

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java [hunk 6]
```diff
@@ -72,6 +70,7 @@ public EngineConfigReader(
         this.expressions = expressions;
         this.schemaTypes = schemaTypes;
         this.logger = logger;
+        this.annotator = new EngineConfigAnnotator();
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java:73]: Please remove this assignment.

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java [hunk 7]
```diff
@@ -190,7 +189,7 @@ private boolean validateAnnotatedSchema(
         validate:
         try
         {
-            final JsonObject annotatedSchemaObject = (JsonObject) annotateJsonObject(schemaObject);
+            final JsonObject annotatedSchemaObject = annotator.annotate(schemaObject);
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java:192]:
```suggestion
            final EngineConfigAnnotator() annotator = new EngineConfigAnnotator();;
            final JsonObject annotatedSchemaObject = annotator.annotate(schemaObject);
```

This should be local because it has internal parse state, no need to carry any potential side effects of previous read to next read.

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
