### PR TITLE
Use flyweight fields instead of class fields for control

### LINKED ISSUE #1004: Flow control issue in openapi binding
**Describe the bug**
Openapi client/server fail to carrry initialSeq and initialAck to complete POST request.

**To Reproduce**
1. Checkout https://github.com/aklivity/zilla-examples/tree/main/openapi.proxy 
2. Follow instruction and start the example
3. Make post request based on openapi petstore api.
4. Requests hangs

**Expected behavior**
Client should succeed.

### PR DESCRIPTION
**Pull request by akrambek**
## Description

Use flyweight fields instead of class fields for control.

Fixes #1004

### CODE REVIEW

File: runtime/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/streams/OpenapiClientFactory.java [hunk 1]
```diff
@@ -407,26 +370,18 @@ private void onOpenapiWindow(
...
+            state = OpenapiState.closingReply(state);
 
-            http.doHttpWindow(traceId, acknowledge, budgetId, padding);
+            http.doHttpWindow(sequence, acknowledge, maximum, traceId, acknowledge, budgetId, padding);
         }
 
         private void doOpenapiBegin(
+            long replySeq,
+            long replyAck,
+            int replyMax,
```
Comment (jfallows) [inline runtime/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/streams/OpenapiClientFactory.java:384]: These parameters should not be _directional_, i.e. `sequence`, not `replySeq`, etc.

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
