### PR TITLE
Better handling negative  edge cases in the connection pool

### LINKED ISSUE #557: [Connection Pool] Signaling can trigger exception
```
2023-10-31 13:44:55 org.agrona.concurrent.AgentTerminationException: java.util.NoSuchElementException
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:707)
2023-10-31 13:44:55     at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
2023-10-31 13:44:55     at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
2023-10-31 13:44:55     at java.base/java.lang.Thread.run(Thread.java:1623)
2023-10-31 13:44:55 Caused by: java.util.NoSuchElementException
2023-10-31 13:44:55     at org.agrona.core/org.agrona.collections.LongArrayQueue.removeLong(LongArrayQueue.java:319)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientConnection.doConnectionWindow(KafkaClientConnectionPool.java:1281)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.flushStreamWindow(KafkaClientConnectionPool.java:886)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.onStreamWindow(KafkaClientConnectionPool.java:783)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientStream.onStreamSignal(KafkaClientConnectionPool.java:1009)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientConnection.onConnectionSignal(KafkaClientConnectionPool.java:1473)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientConnectionPool$KafkaClientConnection.onConnectionMessage(KafkaClientConnectionPool.java:1334)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1119)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:1041)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
2023-10-31 13:44:55     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:701)
2023-10-31 13:44:55     ... 3 more
2023-10-31 13:44:55     Suppressed: java.lang.Exception: [engine/data#9]        [0x09090000000001a3] streams=[consumeAt=0x000fd730 (0x000000000bcfd730), produceAt=0x000fd848 (0x000000000bcfd848)]
2023-10-31 13:44:55             at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:705)
```

### PR DESCRIPTION
**Pull request by akrambek**
## Description

- Added support for better handling those cases, refactored.
- Minor bug fixes in Kafka Client Group Factory

Fixes #557

### CODE REVIEW

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfiguration.java [hunk 1]
```diff
@@ -81,6 +82,7 @@ public class KafkaConfiguration extends Configuration
         KAFKA_CLIENT_INSTANCE_ID = config.property(InstanceIdSupplier.class, "client.instance.id",
             KafkaConfiguration::decodeInstanceId, KafkaConfiguration::defaultInstanceId);
         KAFKA_CLIENT_MAX_IDLE_MILLIS = config.property("client.max.idle.ms", 1 * 60 * 1000);
+        KAFKA_CLIENT_CONNECTION_POLL_CLEANUP_MILLIS = config.property("client.connection.pool.cleanup.millis", 4 * 1000L);
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfiguration.java:85]:
```suggestion
        KAFKA_CLIENT_CONNECTION_POOL_CLEANUP_MILLIS = config.property("client.connection.pool.cleanup.millis", 4 * 1000L);
```

File: runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfigurationTest.java [hunk 2]
```diff
@@ -29,6 +30,8 @@ public class KafkaConfigurationTest
     public static final String KAFKA_CLIENT_PRODUCE_MAX_REQUEST_MILLIS_NAME =
             "zilla.binding.kafka.client.produce.max.request.millis";
     public static final String KAFKA_CLIENT_PRODUCE_MAX_BYTES_NAME = "zilla.binding.kafka.client.produce.max.bytes";
+    public static final String KAFKA_CLIENT_CONNECTION_POLL_CLEANUP_MILLIS_NAME =
```
Comment (jfallows) [inline runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfigurationTest.java:33]:
```suggestion
    public static final String KAFKA_CLIENT_CONNECTION_POOL_CLEANUP_MILLIS_NAME =
```

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
