### PR TITLE
Gracefully handle out of slot exception in kafka client produce

### LINKED ISSUE #558: Gracefully handle out of slot exception in kafka cache client produce
```
2023-11-01 13:27:02 Caused by: java.lang.IllegalArgumentException: invalid offset: -65536
2023-11-01 13:27:02     at org.agrona.core/org.agrona.concurrent.UnsafeBuffer.boundsCheckWrap(UnsafeBuffer.java:1664)
2023-11-01 13:27:02     at org.agrona.core/org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:246)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.buffer.DefaultBufferPool.buffer(DefaultBufferPool.java:136)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory$KafkaProduceStream$KafkaProduceClient.doEncodeRecordInit(KafkaClientProduceFactory.java:1655)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory.flushRecordInit(KafkaClientProduceFactory.java:550)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory$KafkaProduceStream$KafkaProduceClient.flush(KafkaClientProduceFactory.java:1585)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory$KafkaProduceStream.onApplicationData(KafkaClientProduceFactory.java:981)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory$KafkaProduceStream.onApplication(KafkaClientProduceFactory.java:904)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.binding.kafka/io.aklivity.zilla.runtime.binding.kafka.internal.stream.KafkaClientProduceFactory.lambda$newStream$1(KafkaClientProduceFactory.java:257)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1074)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:1041)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
2023-11-01 13:27:02     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:701)
```

### PR DESCRIPTION
**Pull request by akrambek**
## Description

Gracefully handle out of slot exception in kafka client produce

Fixes #558

### CODE REVIEW

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java [hunk 1]
```diff
@@ -583,6 +591,26 @@ private int flushRecordContFin(
         return progress;
     }
 
+    private int rejectAll(
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java:594]:
```suggestion
    private int flushRecordIgnoreAll(
```

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java [hunk 2]
```diff
@@ -583,6 +591,26 @@ private int flushRecordContFin(
...
+        OctetsFW payload,
+        OctetsFW extension,
+        int progress,
+        int limit)
+    {
+        client.cleanupNetwork(traceId);
+
+        progress = limit;
+
+        return progress;
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java:610]:
```suggestion
        return limit;
```

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java [hunk 3]
```diff
@@ -583,6 +591,26 @@ private int flushRecordContFin(
...
+        long authorization,
+        long budgetId,
+        int reserved,
+        int flags,
+        OctetsFW payload,
+        OctetsFW extension,
+        int progress,
+        int limit)
+    {
+        client.cleanupNetwork(traceId);
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java:606]: Can we move this to the place where we assign flusher to `flushRecordIgnoreAll` instead?

**Review by jfallows — CHANGES_REQUESTED** [review]
