### PR TITLE
fix: kafka header extraction expression in composite zilla.yaml

### LINKED ISSUE #1138: Asyncapi kafka header extraction expression don’t match zilla yaml expressions
Currently, it is printing

```
        headers:
          :status: $.status
          zilla:correlation-id: $.correlationid
```

instead of 

```
        headers:
          :status: ${message.value.status}
          zilla:correlation-id: ${message.value.correlationId}
```

### PR DESCRIPTION
**Pull request by ankitk-me**
Fixes #1138

### CODE REVIEW

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicTransformsConfigBuilder.java [hunk 1]
```diff
@@ -89,11 +97,11 @@ public KafkaTopicTransformsConfigBuilder<T> extractHeader(
         if (matcher.reset(path).matches())
         {
             this.extractHeaders.add(new KafkaTopicHeaderType(name,
-                String.format(INTERNAL_VALUE, matcher.group(2))));
+                String.format(INTERNAL_VALUE, matcher.group(2)), externalPath));
         }
         else if (internalMatcher.reset(path).matches())
         {
-            this.extractHeaders.add(new KafkaTopicHeaderType(name, path));
+            this.extractHeaders.add(new KafkaTopicHeaderType(name, path, externalPath));
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicTransformsConfigBuilder.java:104]: When we build the `KafkaTopicTransformsConfig` there should be no matcher used, just capture the parsed values directly and nothing else.

In constructor of `KafkaTopicType`, where we prepare the `KafkaTopicConfig` for use in the binding for each core, that's where the parsed config transforms should be converted as needed to something like `KafkaTopicTransformType` using matcher etc, instead of using parsed transforms config directly.

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
