### PR TITLE
Fix github action

### LINKED ISSUE #23: Investigate GitHub Actions build inconsistencies
The following ITs are failing occasionally when running builds on GitHub Actions, even though local builds are consistently passing.

One option would be to provide access to diagnostic results from `target` directory by uploading them as a zipped artifact using the `upload-artifact` action. Then after the GitHub Actions build breaks again, with artifacts uploaded, we can download those artifacts to diagnose and repair the build by addressing whatever race conditions are causing these IT failures on GitHub Actions only.

See https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#example.

`zilla::runtime::binding-tls` `ClientIT.shouldReceiveServerSentWriteAbort`
https://github.com/aklivity/zilla/runs/6168041575

`zilla::runtime::binding-tls` `ClientIT.shouldReceiveServerSentReadAbort`
https://github.com/aklivity/zilla/runs/6714745603

`zilla::runtime::binding-tls` `ClientIT.shouldReceiveClientSentReadAbort`
https://github.com/aklivity/zilla/actions/runs/2387455848

`zilla::runtime::binding-tcp` `ServerLimitsIT.shouldResetWhenWindowIsExceeded`
https://github.com/aklivity/zilla/runs/6136947505

`zilla::runtime::binding-proxy` `ProxyServerIT.shouldRejectTcp4WithSslUnderflow`
https://github.com/aklivity/zilla/runs/6136454299

`zilla::runtime::binding-proxy` `ProxyServerIT.shouldRejectTcp4WithCrc32cOverflow`
https://github.com/aklivity/zilla/runs/6136437911

`zilla::runtime::binding-proxy` `ProxyServerIT.shouldRejectTcp4WithCrc32cMismatch`
https://github.com/aklivity/zilla/runs/6119880141

`zilla::runtime::binding-proxy` `ProxyServerIT.shouldRejectTcp4WithCrc32cUnderflow`
https://github.com/aklivity/zilla/runs/6566099692

`zilla::runtime::binding-sse` `ReconnectIT.shouldReconnectWithLastEventIdOnEnd`
https://github.com/aklivity/zilla/runs/5647995097

`zilla::runtime::binding-kafka` `CacheMergedIT.shouldFetchMergedMessagesWithNoFilter
https://github.com/aklivity/zilla/actions/runs/2430968606

Ignore failing tests as temporary workarounds 
 - https://github.com/aklivity/zilla/commit/dbf2df4a3fea849ba9c573f253910cd26294739b
 - https://github.com/aklivity/zilla/commit/938251d25c582be421c9b5739ce8bc76fa5e0988
 - https://github.com/aklivity/zilla/commit/6ead20fdc2e51a1eb894cc981a08e76ddcc61894
 - https://github.com/aklivity/zilla/commit/1bafda2e82bf8edefcd483e94251a24fe3a4911d
 - https://github.com/aklivity/zilla/commit/eca9272b61310edfcb489464269473e0eeeb890c

### PR DESCRIPTION
**Pull request by akrambek**
Fix #23

### CODE REVIEW

File: runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/streams/ServerStatsIT.java [hunk 1]
```diff
@@ -65,6 +65,7 @@ public void shouldSendAndReceiveData() throws Exception
         k3po.finish();
 
         EngineStats stats = engine.stats("test", "net0");
+        java.lang.invoke.VarHandle.fullFence();
```
Comment (jfallows) [inline runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/streams/ServerStatsIT.java:68]: Please change this to import `java.lang.VarHandle` instead.

**Review by jfallows — CHANGES_REQUESTED** [review]
Please also search for all other ITs using EngineStats and add the same call to fullFence() there too.

**Review by jfallows — APPROVED** [review]
