### PR TITLE
Bug fixes and improvements to support asyncapi http, sse, and kafka integration

### LINKED ISSUE #1105: Support key validation in kafka asyncapi generation
Currently, we only generate validation for payload we need to support key validation as well.

### PR DESCRIPTION
**Pull request by akrambek**
Fixes #1105

### CODE REVIEW

File: runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiSseProtocol.java [hunk 1]
```diff
@@ -172,15 +172,13 @@ private <C> SsePathConfigBuilder<C> injectValue(
...
-            {
-                AsyncapiMessageView message =
-                    AsyncapiMessageView.of(asyncapi.components.messages, messageEntry.getValue());
-                if (message.payload() != null)
-                {
-                    request.content(injectModel(asyncapi, message));
-                }
-            }
+            request.
+                content(JsonModelConfig::builder)
```
Comment (jfallows) [inline runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiSseProtocol.java:176]: Stylistically, lets put these 2 on the same line.

File: runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/cache/KafkaCachePartition.java [hunk 2]
```diff
@@ -610,7 +622,9 @@ else if (headerTypes != null && !headerTypes.isEmpty())
         }
 
         logFile.appendBytes(headers);
+        final int trailersAt = logFile.capacity();
         logFile.appendBytes(trailers);
+        logFile.readBytes(trailersAt, headersRO::wrap);
```
Comment (jfallows) [inline runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/cache/KafkaCachePartition.java:627]: We can remove this right?

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]

**Review by jfallows — APPROVED** [review]
