### PR TITLE
fix: resolveKind flow for composite binding

### LINKED ISSUE #1406: Java Agent Error while sending Data to Open Telemtry Endpoint (OTEL Endpoint)
### Discussed in https://github.com/aklivity/zilla/discussions/1400

<div type='discussions-op-text'>

<sup>Originally posted by **Gwydiyon** February 13, 2025</sup>
Hey guys, i am a bit lost. Following error occurs while I try sending Logs and Metrics to an OpenTelemetry Collector from my Zilla.

Error in Log: (
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328)
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.serializer.OtlpMetricsSerializer$OtlpMetricsDescriptor.nameByBinding(OtlpMetricsSerializer.java:314)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.serializer.OtlpMetricsSerializer.serializeScalar(OtlpMetricsSerializer.java:161)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.serializer.OtlpMetricsSerializer.serialize(OtlpMetricsSerializer.java:120)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.serializer.OtlpMetricsSerializer.lambda$serializeAll$1(OtlpMetricsSerializer.java:92)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.serializer.OtlpMetricsSerializer.serializeAll(OtlpMetricsSerializer.java:92)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.OltpExporterHandler.exportMetrics(OltpExporterHandler.java:134)
	at io.aklivity.zilla.runtime.exporter.otlp@0.9.125/io.aklivity.zilla.runtime.exporter.otlp.internal.OltpExporterHandler.export(OltpExporterHandler.java:115)
	at io.aklivity.zilla.runtime.engine@0.9.125/io.aklivity.zilla.runtime.engine.internal.exporter.ExporterAgent.doWork(ExporterAgent.java:44)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:304)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.workLoop(AgentRunner.java:296)
	at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

```
zilla.yaml (Zilla-conf)
telemetry:
    # Desired metrics to track
    metrics:
      - http.request.size
      - http.response.size
      - http.active.requests
      - http.duration
      - stream.active.received
      - stream.active.sent
      - stream.opens.received
      - stream.opens.sent
      - stream.data.received
      - stream.data.sent
      - stream.errors.received
      - stream.errors.sent
      - stream.closes.received
      - stream.closes.sent

    exporters:
      otel_exporter_otlp:
        type: otlp
        options:
          interval: 5
          signals:
            - metrics
            - logs
          endpoint:
            protocol: http
            location: http://otel-gw-collector.esb:4318

  bindings:
    #### EVENT
    openapi_event_rest_server:
      type: openapi
      kind: server
      options:
        specs:
          diip_rest_spec:
            catalog:
              openapi_apicurio:
                subject: event
                version: "1"
            servers:
              - url: http://esb-zilla-event.esb:7114
      exit: event_openapi_asyncapi_mapping
      telemetry:
        metrics:
          - stream.*
```

```
otel-collector.conf:
   receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

```
 </div>

### PR DESCRIPTION
**Pull request by ankitk-me**
Fixes #1406

### CODE REVIEW

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineRegistry.java [hunk 1]
```diff
@@ -184,7 +184,7 @@ public Collection<NamespaceRegistry> namespaces()
         return namespacesById.values();
     }
 
-    private NamespaceRegistry findNamespace(
+    public NamespaceRegistry findNamespace(
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineRegistry.java:187]: Can this stay private?

File: runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/NamespaceRegistry.java [hunk 2]
```diff
@@ -89,7 +91,8 @@ public NamespaceRegistry(
         LongConsumer exporterDetached,
         ObjectLongLongFunction<Metric.Kind, LongConsumer> supplyMetricRecorder,
         LongConsumer detachBinding,
-        Collector collector)
+        Collector collector,
+        IntFunction<NamespaceRegistry> findNamespace)
```
Comment (jfallows) [inline runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/NamespaceRegistry.java:95]: Suggest we put this first as it is namespace specific.

**Review by jfallows — COMMENTED** [review]
Can we add a test that verified the metrics are being recorded?

Perhaps via the test binding.

**Review by jfallows — APPROVED** [review]
