### PR TITLE
Flyweight wrapping error race condition fix

### LINKED ISSUE #146: Flyweight wrapping error race condition
**Describe the bug**
Unexpected exception while wrapping header in `HTTP 1.1` response for `404 not found` due to stream `RESET`.

```
org.agrona.concurrent.AgentTerminationException: java.lang.IndexOutOfBoundsException: limit=40 is beyond maxLimit=39
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:586)
2023-01-15 12:06:01     at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
2023-01-15 12:06:01     at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
2023-01-15 12:06:01     at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-15 12:06:01 Caused by: java.lang.IndexOutOfBoundsException: limit=40 is beyond maxLimit=39
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Flyweight.checkLimit(Flyweight.java:67)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.String8FW.wrap(String8FW.java:70)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.HttpHeaderFW.wrap(HttpHeaderFW.java:28)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.HttpHeaderFW.wrap(HttpHeaderFW.java:8)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Flyweight.wrap(Flyweight.java:60)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Array32FW.matchFirst(Array32FW.java:90)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer.doEncodeHeaders(HttpServerFactory.java:2266)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer$HttpExchange.onRequestReset(HttpServerFactory.java:2826)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer$HttpExchange.onExchange(HttpServerFactory.java:2788)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1039)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:967)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:580)
2023-01-15 12:06:01     ... 3 more
2023-01-15 12:06:01     Suppressed: java.lang.Exception: [engine/data#1]        [0x010100000000000d] streams=[consumeAt=0x00000c78 (0x0000000000000c78), produceAt=0x00000c78 (0x0000000000000c78)]
2023-01-15 12:06:01             at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:584)
2023-01-15 12:06:01             ... 3 more
2023-01-15 12:06:01 org.agrona.concurrent.AgentTerminationException: java.lang.IndexOutOfBoundsException: limit=40 is beyond maxLimit=39
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:586)
2023-01-15 12:06:01     at org.agrona.core/org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
2023-01-15 12:06:01     at org.agrona.core/org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
2023-01-15 12:06:01     at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-15 12:06:01 Caused by: java.lang.IndexOutOfBoundsException: limit=40 is beyond maxLimit=39
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Flyweight.checkLimit(Flyweight.java:67)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.String8FW.wrap(String8FW.java:70)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.HttpHeaderFW.wrap(HttpHeaderFW.java:28)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.HttpHeaderFW.wrap(HttpHeaderFW.java:8)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Flyweight.wrap(Flyweight.java:60)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.types.Array32FW.matchFirst(Array32FW.java:90)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer.doEncodeHeaders(HttpServerFactory.java:2263)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer$HttpExchange.onRequestReset(HttpServerFactory.java:2826)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.binding.http/io.aklivity.zilla.runtime.binding.http.internal.stream.HttpServerFactory$HttpServer$HttpExchange.onExchange(HttpServerFactory.java:2788)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleReadInitial(DispatchAgent.java:1039)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.handleRead(DispatchAgent.java:967)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.concurent.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:181)
2023-01-15 12:06:01     at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:580)
2023-01-15 12:06:01     ... 3 more
2023-01-15 12:06:01     Suppressed: java.lang.Exception: [engine/data#2]        [0x020200000000000d] streams=[consumeAt=0x00000c78 (0x0000000000000c78), produceAt=0x00000c78 (0x0000000000000c78)]
2023-01-15 12:06:01             at io.aklivity.zilla.runtime.engine/io.aklivity.zilla.runtime.engine.internal.registry.DispatchAgent.doWork(DispatchAgent.java:584)
2023-01-15 12:06:01             ... 3 more
2023-01-15 12:06:01 stopped
```

**To Reproduce**
1. Use `http.echo` example
2. In `zilla.json`, change `http_server0` exit to `"none"`
3. Start the docker stack per README
4. `echo "Hello, world" > /tmp/postfile`
5. Use `ab -v 4 -n 20 -c 20 -p /tmp/postfile -T "text/plain" -m "POST" http://localhost:8080/` to trigger bug
**Expected behavior**
Zilla should not trigger an exception.

**Additional context**
This is triggered because when stream `RESET` occurs, in this case due to `exit` binding not found, we automatically send a `404 not found response`, based on static field `HEADERS_404_NOT_FOUND` in `HttpServerFactory`.

During encode, the `HTTP 1.1` server factory uses the `matchFirst` method on the headers, which mutates the internal header item flyweight, causing a race condition across threads.

Note: this bug no longer reproduces when `zilla` is configured via `stack.yml` to use one thread only, via `-w 1` command line argument which sets workers to 1.

### PR DESCRIPTION
**Pull request by aDaemonThread**
fix #146

### CODE REVIEW

File: runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java [hunk 1]
```diff
@@ -6655,6 +6647,24 @@ private static Array32FW<HttpHeaderFW> initHeaders(
...
+        final Array32FW.Builder<HttpHeaderFW.Builder, HttpHeaderFW> builder =
+                new Array32FW.Builder<>(new HttpHeaderFW.Builder(), new HttpHeaderFW())
+                        .wrap(new UnsafeBuffer(new byte[64]), 0, 64)
+                        .item(h -> h.name(HEADER_STATUS).value(status));
+
+        final String16FW server = config.serverHeader();
+        if (server != null)
+        {
+            builder.item(h -> h.name(HEADER_SERVER).value(server));
+        }
```
Comment (aDaemonThread) [inline runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java:6663]: @jfallows Do you think we need to update `HEADER_SERVER` as well? In the earlier static declaration we don't have this attribute?

Comment (aDaemonThread) [reply runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java]: Update: Removed `HEADER_SERVER` attribute from newly added method `initHeadersEmpty` as it was causing the related ITs to fail.

**Review by jfallows — APPROVED** [review]

File: runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java [hunk 2]
```diff
@@ -6655,6 +6643,19 @@ private static Array32FW<HttpHeaderFW> initHeaders(
...
 
+    private static Array32FW<HttpHeaderFW> initHeadersEmpty(
+            HttpConfiguration config,
+            String16FW status)
+    {
+        final Array32FW.Builder<HttpHeaderFW.Builder, HttpHeaderFW> builder =
+                new Array32FW.Builder<>(new HttpHeaderFW.Builder(), new HttpHeaderFW())
+                        .wrap(new UnsafeBuffer(new byte[64]), 0, 64)
+                        .item(h -> h.name(HEADER_STATUS).value(status));
+
```
Comment (jfallows) [inline runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java:6654]: Let's include the `server` header when explicitly specified, same as `initHeaders`.

**Review by jfallows — CHANGES_REQUESTED** [review]

**Review by jfallows — APPROVED** [review]
